name: munchkinhalfling/hc-hello
sourceType: git
source: git://github.com/munchkinhalfling/hc-hello.git
scripts:
  build:x
    - make
  install:
    - make install PREFIX=$(PREFIX)
bin:
  hubcap-hello: bin/hubcap-hello
